# Generated by Django 5.2.2 on 2025-08-24 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата операции")),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Доход"), ("expense", "Расход")],
                        max_length=7,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Наличные"),
                            ("card", "Карта"),
                            ("online", "Онлайн-платёж"),
                            ("other", "Другое"),
                        ],
                        max_length=10,
                        verbose_name="Способ оплаты/получения",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("BYN", "Белорусский рубль"),
                            ("RUB", "Российский рубль"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                        ],
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "tag",
                    models.CharField(blank=True, max_length=50, verbose_name="Метка"),
                ),
                ("category", models.CharField(max_length=50, verbose_name="Категория")),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Подкатегория"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
