# Generated by Django 5.2.2 on 2025-08-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="position",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_link_code",
            field=models.CharField(
                blank=True,
                max_length=36,
                unique=True,
                verbose_name="Код привязки Telegram",
            ),
        ),
    ]
