# Generated by Django 5.2.2 on 2025-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_position_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_link_code",
            field=models.CharField(
                blank=True,
                max_length=36,
                null=True,
                unique=True,
                verbose_name="Код привязки Telegram",
            ),
        ),
    ]
