# Generated by Django 5.2.2 on 2025-08-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_telegram_link_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_link_code",
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Telegram username",
            ),
        ),
    ]
